version: '3'

services:
  reverse:
    container_name: reverse
    hostname: my-host
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy/conf:/etc/nginx
      - ./reverse-proxy/certs:/etc/ssl
      # - ./app:/usr/local/nginx/html
    links: 
      - app1

  app1:
      image: mendhak/http-https-echo
      hostname: app1
      ports:
          - "8080:80"
          - "8443:443"

  myApp:
      image: nginx
      hostname: myApp
      ports:
          - "8090:80"
          - "8493:443"
      volumes:
        - ./myApp/conf/html:/etc/nginx/html
        - ./reverse-proxy/certs:/etc/ssl